bcgov/business-dashboard-ui

.env.example
nuxt.config.ts

*Issue:*https://github.com/bcgov/entity/issues/21296

tweaked config

---

src/components/bcros/Section.vue
src/lang/en.json
src/pages/dashboard.vue
tests/pages/dashboard.spec.ts
tests/test-utils/mockedi18n.ts

*Issue:*https://github.com/bcgov/entity/issues/21298
Add the section component and set up dashboard layout

Section component and dashboard layout

---

cypress/e2e/components/custodian-of-records.cy.ts
cypress/e2e/components/directors-partners-proprietors.cy.ts
cypress/fixtures/custodianOfRecords.json
cypress/support/commands.ts
src/components/bcros/AccordionItem.vue
src/components/bcros/OfficeAddress.vue
src/components/bcros/PartyInfo.vue
src/lang/en.json
src/pages/dashboard.vue
src/utils/error-dialog-options/auth-access-error.ts
src/utils/error-dialog-options/default-error.ts
src/utils/error-dialog-options/download-file-error.ts

*Issue:*https://github.com/bcgov/entity/issues/21926
To view an example of Custodian of Records section, use BC0882321

Custodian of Records section

---

.github/workflows/cd.yml
src/components/bcros/AddressDisplay.vue

Address display fix for bor-ui case

---

src/composables/useBcrosNavigate.ts

common redirect update

---

src/components/bcros/businessDetails/Status.vue
src/stores/business.ts

*Issue:22369 *https://github.com/bcgov/entity/issues/22369 
- fix issue with message text.

22369 - fixing issue with missing message text.

---

src/components/bcros/todo/Item.vue
src/components/bcros/todo/List.vue
src/components/bcros/todo/content/ChangedRequested.vue
src/components/bcros/todo/content/Error.vue
src/components/bcros/todo/content/NotInGoodStanding.vue
src/components/bcros/todo/content/Paid.vue
src/components/bcros/todo/content/Pending.vue
src/components/bcros/todo/expansion-content/Affiliation.vue
src/components/bcros/todo/expansion-content/ChangeRequested.vue
src/components/bcros/todo/expansion-content/ConversionDetails.vue
src/components/bcros/todo/expansion-content/CorrectionComment.vue
src/components/bcros/todo/expansion-content/PaymentIncomplete.vue
src/components/bcros/todo/expansion-content/PaymentPaid.vue
src/components/bcros/todo/expansion-content/PaymentPending.vue
src/components/bcros/todo/expansion-content/PaymentPendingOnlineBanking.vue
src/components/bcros/todo/expansion-content/PaymentUnsuccessful.vue

Re-order the tags in todo components. Script - Template - Style

Template Flip - Todo components

---

cypress/e2e/components/tombstone/digital-credentials.cy.ts
cypress/fixtures/businessInfo/sp/withDigitalCredential.json
src/components/bcros/businessDetails/LinkActions.vue

*Issue:*https://github.com/bcgov/entity/issues/21697

Digital Business Card button redirection

---

cypress/e2e/layout/breadcrumb.cy.ts
src/app/router.options.ts
src/components/bcros/Breadcrumb.vue
src/components/bcros/businessDetails/LinkActions.vue
src/composables/useBcrosNavigate.ts
src/lang/en.json
src/layouts/business.vue
src/layouts/default.vue
src/utils/breadcrumbs.ts

*Issue:*https://github.com/bcgov/entity/issues/21789
*Description of changes:
- Update breadcrumb view for staff dashboard
- Move the redirect logic for digital business card to the composable.

Update breadcrumb for staff dashboard

---

src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/22891
Remove by means of comment the disabled alert in the dashboard, this is temporary until we decide if a disabled alert is needed and what the conditions for said alert are

Remove Disabled alert

---

src/components/bcros/OfficeAddress.vue
src/components/bcros/accordion/Index.vue

Flips template and script in files touched by pending change of address ticket

Template flip - address change

---

cypress/e2e/components/legalObligations.cy.ts
cypress/fixtures/bootstrapFiling.json
cypress/support/commands.ts
src/components/bcros/LegalObligation.vue
src/components/bcros/todo/List.vue
src/lang/en.json
src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/22258
examples can be accessed using IDIR login
"Business Corporations Act"
- https://dev.business.bcregistry.gov.bc.ca/BC0871495
- https://dev.business.bcregistry.gov.bc.ca/BC0883571
"Partnership Act"
- https://dev.business.bcregistry.gov.bc.ca/FM1060548
example of no legal obligations box (even when there is no todo task)
- https://dev.business.bcregistry.gov.bc.ca/BC1218890

legal obligations component

---

src/components/bcros/businessDetails/index.vue

business details alignment fix

---

cypress/e2e/components/todos/annual-report-filing.cy.ts
src/utils/todo/action-functions.ts

*Issue:*https://github.com/bcgov/entity/issues/23095

AR routing redirect

---

cypress/e2e/components/filings/addStaffFiling.cy.ts
cypress/fixtures/businessInfo/ben/active.json
src/components/bcros/filing/AddStaffFiling.vue
src/lang/en.json
src/pages/dashboard.vue
src/stores/filings.ts
src/types/create-filing.ts

*Issue:*https://github.com/bcgov/entity/issues/21786

add ability for staff to freeze and unfreeze

---

cypress/e2e/components/filings/section.cy.ts
cypress/fixtures/filings/staffFiling/adminFreeze.ts
src/components/bcros/filing/List.vue
src/lang/en.json

*Issue:23439*https://github.com/bcgov/entity/issues/23439
*Issue:23197*https://github.com/bcgov/entity/issues/23197 
- fixed 2 minor bugs
- missing text for ULC type of company in the tombstone
- removed freeze/unfreeze from being displayed (when they have `displayLedger `set to false)

23439; 23197 - Bug fixing

---

cypress.config.ts
cypress/e2e/components/tombstone/menu-options.cy.ts
cypress/support/commands.ts
src/components/bcros/businessDetails/Links.vue
src/stores/filings.ts

*Issue:*https://github.com/bcgov/entity/issues/23467
Implement dissolve business functionality and tests

dissolve business

---

cypress/e2e/components/addresses.cy.ts
src/components/bcros/dialog/CardedModal.vue
src/interfaces/dialog-options-i.ts
src/lang/en.json
src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/21889
Added a carded (UCard) dialog option, added dialog that shows on change address. Added redirection rules for addresses and director changes in all cases. NOTE this does not implement a page for those in this dashboard those pages still only exist in the current/older dashboard

change address and director handling

---

src/components/bcros/filing/item/DissolutionVoluntary.vue
src/interfaces/alert-i.ts
src/lang/en.json
src/pages/dashboard.vue
src/utils/alert.ts

*Issue:*https://github.com/bcgov/entity/issues/23873

Fix future effective amalgamation alert

---

src/utils/todo/action-functions.ts

*Issue:*https://github.com/bcgov/entity/issues/24291
Update 'resume' button for restoration to-do

Update 'resume' button for restoration to-do

---

cypress/e2e/components/addresses.cy.ts
src/components/bcros/tooltip/index.vue
src/lang/en.json
src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/24212
Add tooltip for 'Pending' in address component

Add tooltip for the 'Pending' tag in Address section

---

src/stores/account.ts

*Issue:24289 *https://github.com/bcgov/entity/issues/24289 
fix: what roles are being tested for authorizing access.

24289 - fix: what roles are being tested for authorizing access.

---

src/stores/business.ts

*Issue:*https://github.com/bcgov/entity/issues/24525
The detection for the restoration state included full restoration instead of extended which was the intended state. This fixes that

fix logic for limited restoration

---

src/components/bcros/ContactInfo.vue
src/components/bcros/alert/index.vue
src/lang/en.json

*Issue:24438 *https://github.com/bcgov/entity/issues/24438 
- fix: remove extra contact from frozen alert; 
- fix spelling.

24438 - fix: remove extra contact from frozen alert; fix spelling.

---

src/app.config.ts
src/components/bcros/businessDetails/LinkActions.vue

*Issue:24512 *https://github.com/bcgov/entity/issues/24512 
style: updating ubutton styles when disabled.

24512 - style: updating ubutton styles when disabled.

---

src/components/bcros/header/Index.vue
src/middleware/02.setupAuth.global.ts

*Issue:24755*https://github.com/bcgov/entity/issues/24755
fix: when and how is account fetched.

24755 - fix: when and how is account fetched.

---

src/components/bcros/header/Index.vue
src/middleware/02.setupAuth.global.ts

fix: issue when there are multiple accountid query params.

fix: issue when there are multiple accountid query params.

---

src/lang/en.json

*Issue:*https://github.com/bcgov/entity/issues/24518
Added translation

fix loading screen text

---

src/utils/todo/action-functions.ts

*Issue:*https://github.com/bcgov/entity/issues/24819
Add business identifier to the url path so the redirection is working. 
See this example: https://business-dashboard-dev--pr-106-7f2yso96.web.app/BC0883735  (accessed by IDIR)
Click the "Resume" button and get to the voluntary dissolution filing page. 

24819 - fix redirection for voluntary dissolution draft

---

src/components/bcros/businessDetails/Links.vue
src/stores/filings.ts

fix:
- wrong redirect
- missing start date for filings.

24817 - fix: wrong redirect; missing start date for filings.

---

src/components/bcros/todo/Item.vue
src/utils/todo/action-functions.ts

*Issue:24921 *https://github.com/bcgov/entity/issues/24921 
fix:
- cancel payment
- resume sole prop

24921 - fix: cancel payment, resume sole prop

---

.github/CODEOWNERS

chore: adding codeowners

---

package.json
src/components/bcros/filing/common/DetailsList.vue

*Issue:*https://github.com/bcgov/entity/issues/25158
Preserve Line Breaks for Detail comments

25158  - Preserve Line Breaks for Detail comments

---

package.json
src/components/bcros/filing/common/HeaderActions.vue

*Issue:*https://github.com/bcgov/entity/issues/25406
- Disable "File a Withdrawal" action from drop-down when feature flag is **false**

25406-Add Enable-Withdrawal-Action Feature Flag

---

package.json
src/components/bcros/filing/common/HeaderActions.vue
src/interfaces/bootstrap-i.ts
src/interfaces/filing-i.ts
src/stores/filings.ts

*Issue:*https://github.com/bcgov/entity/issues/25578
- Disable the Withdraw Action from drop-down when the withdrawnPending property is True

25578 - Disable Withdraw Action when Filing has a Pending NoW

---

package.json
src/components/bcros/filing/common/HeaderActions.vue
src/stores/documents.ts

*Issue:*https://github.com/bcgov/entity/25258
- Catch errors from trying to fetch DRS on a TEMP REG identifier

25258- Catch Temp Reg DRS GET error

---

package.json
src/lang/en.json
src/pages/dashboard.vue
src/stores/businessBootstrap.ts

*Issue:*https://github.com/bcgov/entity/issues/25810 
- Add missing status to `isAmalgamationFiling `
- Add check for bootstrap identifier on retry mechanism

25810 - Fix Empty Dashboard for Amalgamation

---

package.json
src/components/bcros/filing/common/filedAnd/Withdrawn.vue
src/interfaces/bootstrap-i.ts
src/interfaces/filing-i.ts
src/stores/filings.ts

*Issue:*https://github.com/bcgov/entity/issues/25886
- Show Withdrawn Date for regular filings
- Show Withdrawn Date for temp business withdrawn

25886 - Show Withdrawn Date for withdrawn filings

---

cypress/e2e/components/filings/addStaffFiling.cy.ts
package.json
src/components/bcros/filing/addStaffFiling/Index.vue
src/components/bcros/filing/addStaffFiling/modal/Form.vue
src/utils/todo/action-functions.ts

*Issue:*bcgov/entity#25189
reroute the court order filing

25189 - Business Dashboard: delete local Court Order dialog and route to single page filing instead (DO THIS LAST)

---

package.json
src/components/bcros/businessDetails/LinkActions.vue
src/components/bcros/filing/addStaffFiling/Index.vue

*Issue:* bcgov/entity#25189
*Description of changes:* regenerate court order url from filing ui

25189 regenrate filing ui url for co

---

package.json
src/app.config.ts

*Issue:*bcgov/entity#25874
toast positioned to bottom

25874 fixed toast position to bottom center

---

package.json
src/components/bcros/filing/item/CourtOrderFiling.vue

*Issue:*bcgov/entity#25697
Business Dashboard: updates to display Court Order receipt in ledger

25697 Business Dashboard: updates to display Court Order receipt in ledger

---

package.json
src/components/bcros/filing/addStaffFiling/modal/freezeUnfreeze.vue
src/pages/dashboard.vue

*Issue:*bcgov/entity#25518
restart slim calls on freeze unfreeze filings

25518 - Business Dashboard: retries not restarting after Freeze or Unfreeze

---

.github/CODEOWNERS
.github/workflows/ci.yml
cypress/e2e/components/tombstone/statuses.cy.ts
package.json
pnpm-lock.yaml

*Issue:* bcgov/entity#26205
- updated CI script to run on Ubuntu 24.04
- no app version change needed because there is no UI change
- split up "statuses" test suite to debug it (which fixed it)
- updated CODEOWNERS
- updated browsers list

26205 Updated CI script, etc

---

package.json
src/components/bcros/todo/Item.vue

*Issue:*bcgov/entity#26070
redirection to brd

26070  redirect to brd

---

package.json
src/utils/download-file.ts

*Issue:*bcgov/entity#26236
A unit test is failing (probably related to recent changes). This test case needs to be fixed.
court order application number show in ledger

26236 unit test fix court order

---

package.json
src/components/bcros/filing/item/DissolutionVoluntary.vue

*Issue:*https://github.com/bcgov/entity/issues/26219
- Fix the bug: When a VD filing is withdrawn by filing a NOW then the Withdrawn status is not showing 

26219 - Show Withdrawn Status for VD

---

package.json
src/components/bcros/todo/Item.vue

*Issue:*https://github.com/bcgov/entity/issues/25826
Adding in some max and min size restrictions in order to keep button from overflowing.

25826 spaceing issue fix for chevron button

---

package.json
src/components/bcros/filing/item/ConsentContinuationOut.vue
src/components/bcros/filing/item/ContinuationOut.vue

*Issue:*https://github.com/bcgov/entity/issues/26300
- Fix the bug described in the ticket, by fixing a TypeError

26300 - Fix the ContOut & Consent to ContOut Expand Bug

---

package.json
src/components/bcros/filing/item/AlterationFiling.vue
src/components/bcros/filing/item/ConsentContinuationOut.vue
src/components/bcros/filing/item/ContinuationOut.vue
src/components/bcros/filing/item/DissolutionVoluntary.vue
src/components/bcros/filing/item/LimitedRestoration.vue

*Issue:*https://github.com/bcgov/entity/issues/26293
- Jacqueline said reduce the space from 24 px to 16 px
- And add a space for Consent to ContOut too

Fix 26293 - Adjust Space in Filing History

---

package.json
src/pages/dashboard.vue
src/stores/todo.ts

*Issue:*bcgov/entity#25388
Business Dashboard: To Do list displays a few seconds after spinner hides

25388 todo list delays

---

package.json
src/components/bcros/todo/Item.vue

*Issue:*https://github.com/bcgov/entity/issues/25826
Quick update to ensure button stays right rather than pulling to the left when titles are short.

25826-Update to keep button to the right of the box.

---

package.json
src/composables/useBcrosNavigate.ts

*Issue:*https://github.com/bcgov/entity/issues/24822
Adding businessid value to url.

24822 adding businessid value to query string

---

package.json
src/utils/download-file.ts

*Issue:*https://github.com/bcgov/entity/issues/25320
- Change file name from "Undefined BC Community Contribution" to "Txxxxx BC Community Contribution"

25320 - Show T Number in file name for temp business

---

nuxt.config.ts
package.json

*Issue:*bcgov/entity#26390
Business Dashboard: fix tab title

26390 - Update Title Page Nuxt App

---

cypress/e2e/components/filings/addStaffFiling.cy.ts
cypress/e2e/components/todos/annual-report-filing.cy.ts
cypress/e2e/components/todos/draft.cy.ts
cypress/fixtures/filings/addressChange/completed.ts
package.json
src/utils/breadcrumbs.ts

*Issue:* bcgov/entity#26499
- app version = 1.0.33
- added account id to BCROS home crumb
- fixed unit tests

26499 fixed BCROS breadcrumb + fixed Cypress tests

---

package.json
src/utils/todo/task-filing/button-loader.ts

*Issue:*https://github.com/bcgov/entity/issues/26606 

26606 - Allow Resume Draft for Regular User for Voluntary Dissolution

---

cypress/e2e/components/filings/addStaffFiling.cy.ts
cypress/fixtures/businessFilingsHistorical.json
cypress/fixtures/slim.json
cypress/support/commands.ts
package.json
src/app.vue
src/app/router.options.ts
src/components/bcros/dialog/Index.vue
src/lang/en.json
src/pages/dashboard.vue
src/pages/errors.vue
src/stores/business.ts
src/stores/todo.ts
src/utils/error-dialog-options/index.ts
src/utils/error-dialog-options/not-found-error.ts
src/utils/error-dialog-options/page-not-found-error.ts
src/utils/todo/affiliation.ts

*Issue:*bcgov/entity#26289
Business Dashboard: should handle error if business id is invalid
redirect to staff dashboard

26289 - Business Dashboard: should handle error if business id is invalid

---

package.json
src/components/bcros/businessDetails/Status.vue
src/components/bcros/filing/List.vue
src/components/bcros/filing/addStaffFiling/Index.vue
src/components/bcros/filing/item/AmalgamationOut.vue
src/components/bcros/filing/item/ConsentAmalgamationOut.vue
src/interfaces/filing-i.ts
src/lang/en.json
src/stores/filings.ts
src/utils/todo/action-functions.ts
src/utils/todo/task-filing/button-loader.ts
src/utils/todo/task-filing/content-loader.ts
src/utils/todo/task-filing/helper.ts

*Issue:*https://github.com/bcgov/entity/issues/26822
For both Consent to Amalgamation Out and Record of Amalgamation Out:
- Update the language in filing history ledger
- Show the "AUTHORIZED TO AMALGAMATE OUT" badge
- Display the Resume/Delete button for a draft (staff only), regular user can't Resume/Delete

26822 - Updates for Consent Amalgamation Out / Record Amalgamation Out

---

cypress/e2e/components/directors-partners-proprietors.cy.ts
package.json
src/components/bcros/Address.vue
src/components/bcros/OfficeAddress.vue
src/lang/en.json
src/pages/dashboard.vue
src/stores/business.ts
src/stores/businessBootstrap.ts

*Issue:* bcgov/entity#26948
- app version = 1.0.38a
- address special case for address not found
- added check for delivery address before displaying it, else display "not entered"
- added check for mailing address before displaying it, else display "not entered"
- used hasOwnProperty() to check for null object (x2)
- changed "Priorietors" to "Proprietor"
- misc cleanup
- fixed Cypress test
- changed object.hasOwnProperty() to Object.hasOwn() (x2)

26948 added special case for address not found

---

package.json
src/app.vue
src/components/bcros/filing/item/ContinuationOut.vue
src/components/bcros/filing/item/StaffFiling.vue
src/interfaces/dialog-options-i.ts
src/lang/en.json

*Issue:* bcgov/entity#26640, bcgov/entity#26904, bcgov/entity#26868 and bcgov/entity#26903
First commit:
- app version = 1.0.45
- fixed wrong legal name in template
Second commit:
- added some legal type strings
Third commit:
- added Error Info property "contact"
- set "contact" when errorContactInfo is True
- use "contact" in dialog
- updated interface
- added and updated strings for Load Business Fetch Error
Fourth commit:
- added "Filed and Pending" if not completed

26640, 26904, 26868 and 26903 - Misc small fixes

---

cypress/e2e/components/tombstone/business-details.cy.ts
package.json
src/components/bcros/businessDetails/index.vue
src/lang/en.json
src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/26797
Making sure that you can add directors even if no exist currently. Includes update to check if it is a relevant company type, and if so the Directors section always shows.

26797-Allowing director heading if proper business type

---

src/components/bcros/businessDetails/index.vue

*Issue:*https://github.com/bcgov/entity/issues/26620
Update to formatting in the case of long emails addresses. 

26620-Updating to formatting for long email addresses

---

package.json

*Issue:*https://github.com/bcgov/entity/issues/26620
Incrementing version number which was missed in PR 180. 

26620 quick PR to bring version number back in line, missed in PR 180

---

package.json
src/utils/download-file.ts

*Issue:*https://github.com/bcgov/entity/issues/27133
- update the text to display "Letter of Consent" (remove "Amalgamation Out") for document name

27133 - Show "Letter of Consent" for Amalg Out consent letter in Document List

---

package.json
src/components/bcros/alert/index.vue
src/lang/en.json

*Issue:*https://github.com/bcgov/entity/issues/25907

25907 - Fix Date in Business Dissolution Alert

---

package.json
src/lang/en.json

*Issue:*https://github.com/bcgov/entity/issues/27353

27353 update amalgamation out text

---

package.json
src/components/bcros/filing/item/AmalgamationOut.vue

*Issue:*https://github.com/bcgov/entity/issues/27540
- For Amalgamation Out filing ledger
- Display Business Name in New Jurisdiction

27540 - Display Business Name in New Jurisdiction

---

package.json
src/components/bcros/filing/item/StaffFiling.vue

*Issue:*https://github.com/bcgov/entity/issues/27532 
- Remove duplicate code to display Court Order and POA
Before:
After:

27532 - Fix Duplicate Court Order and POA for Put Back On Filing

---

package.json
src/components/bcros/dialog/CardedModal.vue
src/components/bcros/dialog/Index.vue
src/components/bcros/dialog/slot-templates/DialogButton.vue
src/components/bcros/todo/Item.vue

*Issue:*https://github.com/bcgov/entity/issues/27240
Add the loading state in to Dialog Button

27240 add_loading_state_button

---

package.json
src/lang/en.json

*Issue:*https://github.com/bcgov/entity/issues/28454
- Online banking payee name update
- Online banking payment identifier text update

28454 - Online Banking Wording updates

---

package.json
src/components/bcros/AddressDisplay.vue
tests/components/bcros/BcrosAddressDisplay.spec.ts

*Issue:*https://github.com/bcgov/entity/issues/27611

27611 - StreetAddressAdditional Field not Displaying

---

package.json
src/pages/dashboard.vue

*Issue:*https://github.com/bcgov/entity/issues/27544 
- Stop polling on refresh/reload to cancel the previous timeout (causing the extra snackbar to appear)

27544 - Snackbar Reappears Sometimes after Refresh

---

package.json
src/components/bcros/filing/addStaffFiling/Index.vue

*Issue:*https://github.com/bcgov/entity/issues/29002 

29002 update Add_Staff_Filing button menu

---

cypress/e2e/accessibility/business-dash.cy.ts
cypress/e2e/components/filings/addStaffFiling.cy.ts
cypress/e2e/components/filings/section.cy.ts
cypress/e2e/error-flows/entry-auth-error.cy.ts
cypress/e2e/initial-page-load.cy.ts
cypress/support/commands.ts
src/middleware/03.setupAuth.global.ts

*Issue:*https://github.com/bcgov/entity/issues/29206

29206 fix_cypress_tests

---

package.json
src/stores/account.ts
src/stores/business.ts
src/stores/businessBootstrap.ts
src/stores/filings.ts
src/stores/todo.ts

*Issue:*https://github.com/bcgov/entity/issues/30174
Part -1: Business API GW calls
Fix function getBusinessAddress()
Fix other Business API GW calls that reference error.value?.data?.message -> error.value?.data?.rootCause?.message
Change app version to 1.1.11a

30174 hotfix missing address loading fails-1
