bcgov/business-dashboard-ui

nuxt.config.ts, src/app.config.ts, src/app/router.options.ts, src/assets/styles/layout.scss, src/components/bcros/Breadcrumb.vue, src/components/bcros/BusinessDetails.vue, src/components/bcros/Footer.vue, src/components/bcros/SystemBanner.vue, src/components/bcros/header/Index.vue, src/layouts/business.vue, src/layouts/default.vue
*Issue:*https://github.com/bcgov/entity/issues/21296
=> minor cleanup in prep for consolidation across projects

cypress/e2e/components/filings/section.cy.ts, cypress/fixtures/filings/directorChange/commentList.json, cypress/fixtures/filings/directorChange/directorChange.ts, src/components/bcros/filing/CommonTemplate.vue, src/components/bcros/filing/common/DetailsList.vue, src/components/bcros/filing/common/DocumentsList.vue, src/utils/filings.ts
*Issue:21802 *https://github.com/bcgov/entity/issues/21802 
- add details button
- comments visible
- prepared code for putting in popup
- tests
=> 21802 - Add details call and list.

cypress/e2e/components/addresses.cy.ts, src/components/bcros/OfficeAddress.vue, src/components/bcros/accordion/Index.vue, src/lang/en.json, src/pages/dashboard.vue, tailwind.config.ts
*Issue:*https://github.com/bcgov/entity/issues/22690
If the business has a pending address change filing the addresses will show with the pending badge, the section will be tinted yellow and the change address button will be disabled. Tests added/modified to verify badge shows up and doesn't show up as expected
=> pending address change

src/interfaces/business-i.ts, src/pages/dashboard.vue
*Issue:23439 *https://github.com/bcgov/entity/issues/23439 
*Description of changes:23439 *
- disable change buttons on address and directors when business is in freeze
=> 23439 - bug fixing

src/components/bcros/businessDetails/Links.vue, src/components/bcros/businessDetails/Status.vue, src/components/bcros/dialog/CardedModal.vue, src/lang/en.json
*Issue:*https://github.com/bcgov/entity/issues/23472
https://github.com/bcgov/entity/issues/22292
Added the dialog that appears when trying to dissolve a business that is not in good standing. Note however that I sort of needed to force my way into that workflow as none of the not in good standing businesses were returning that that filing was allowed which disables the button.
=> Not in good standing dissolution dialog box

src/components/bcros/filing/addStaffFiling/Index.vue
*Issue:*https://github.com/bcgov/entity/issues/23491
Set restoration filing type to draft (we were already using null and it works fine once the filing is draft)
=> fix restore to use draft filing

cypress/e2e/components/todos/draft.cy.ts, cypress/fixtures/todos/draft/voluntaryDissolution.json, src/utils/todo/task-filing/button-loader.ts, src/utils/todo/task-filing/content-loader.ts
*Issue:*https://github.com/bcgov/entity/issues/23569
Fix the bug for a draft voluntary dissolution, to properly display the title and action button. Mismatch resolved.
=> Bug fix - To do Draft for Voluntary Dissolution

cypress/e2e/components/todos/pending.cy.ts, cypress/fixtures/todos/pendingAdminFreeze.json, cypress/fixtures/todos/pendingRegistrarsNotation.json, src/utils/todo/task-filing/content-loader.ts
*Issue:*https://github.com/bcgov/entity/issues/23495
*Issue:*https://github.com/bcgov/entity/issues/23634
This bug is hard to reproduce as a staff filing does not get the pending status very often. To verify the bug has been resolved, pending filings are mocked in cypress test. The following screenshots are taken locally:
Pending Admin Freeze:
Pending Registrar's Notation - Collapsed:
Pending Registrar's Notation - Expanded (staff account users will not see the contact info section)
Pending Registrar's Notation - Expanded (non-staff users can see the contact info section)
=> Bug fix - Pending staff filings in to-do

cypress/e2e/components/filings/addStaffFiling.cy.ts, cypress/fixtures/businessInfo/bc/historical.json, cypress/fixtures/businessInfo/sp/active.json, src/components/bcros/filing/addStaffFiling/Index.vue, src/stores/business.ts
*Issue:*https://github.com/bcgov/entity/issues/23820
Update the display logic for the menu options in the "Add Staff Filing" dropdown, using the same logic as the old codebase (https://github.com/bcgov/business-filings-ui/blob/3a62b2b470bf16c181b879057823ff795e5faf68/src/components/Dashboard/StaffNotation.vue#L85-L230)
Major update: instead of calling the `isAllowedToFile(FilingTypes)`, use the wrapper function `isAllowed(AllowableActionE)`
=> Bug fix - mismatches in the staff filing dropdown menu

src/components/bcros/businessDetails/Status.vue, src/lang/en.json
*Issue:*https://github.com/bcgov/entity/issues/24011
Update the i18n so the dissolution type can be displayed correctly in the tombstone of a historical business. 
=> Bug fix - voluntary dissolution text in tombstone

src/components/bcros/filing/item/DissolutionVoluntary.vue
*Issue:*https://github.com/bcgov/entity/issues/23976
Added spacing between the lines in filing, added the fallback case for when it's paid and effective now, removed the switch between entityFirm and !entityFirm text as it was not correct. 
=> Voluntary Dissolution filing display changes

cypress/e2e/components/tombstone/business-details.cy.ts, src/components/bcros/businessDetails/index.vue, src/composables/useBcrosNavigate.ts, src/lang/en.json, src/stores/business.ts
*Issue:*https://github.com/bcgov/entity/issues/23859
Update the Business Details section in the dashboard tombstone
- Display 'Registration Date' for SP and GP
- Add 'Change' buttons to Email and Phone
- refine the order of the info list
-- SP/GP:  Registration Date -> Registration Number -> Business Number -> Email -> Phone
-- Other:  Business Number -> Incorporation Number -> Email -> Phone
- Add i18n text for legal type 'C'
Note: 'Change' buttons redirect to https://dev.account.bcregistry.gov.bc.ca/businessprofile  but the page cannot be loaded (possibly) due to missing sessionStorage values
*Issue:*https://github.com/bcgov/entity/issues/24290
- Add i18n text for legal type 'C'
By submitting this pull request, I confirm that you can …
=> update the business details section in tombstone

src/components/bcros/filing/item/AgmExtension.vue
*Issue:*https://github.com/bcgov/entity/issues/24442
- fix date display in AgmExtension filing
To view an example of AgmExtension filing, visit https://dev.business.bcregistry.gov.bc.ca/BC0883710
=> fix date display in AgmExtension filing

src/components/bcros/businessDetails/Links.vue, src/components/bcros/businessDetails/index.vue, src/components/bcros/filing/CommonTemplate.vue, src/components/bcros/filing/common/DetailsList.vue, src/components/bcros/header/Index.vue, src/components/bcros/todo/expansion-content/CorrectionComment.vue, src/pages/errors.vue, tailwind.config.ts
*Issue:24289 *https://github.com/bcgov/entity/issues/24289 
fix style for flexgrid to wrap on small sized screens and smaller
=> 24289 - style: fix flexgrid to wrap on small sized screens and smaller

cypress/e2e/components/comments.cy.ts, src/components/bcros/businessDetails/Links.vue, src/components/bcros/comment/Index.vue
*Issue:*https://github.com/bcgov/entity/issues/24292
Fix the bug so the cancel button in the staff comment modal is working.
=> enable 'cancel' button in the comment modal

src/components/bcros/businessDetails/Links.vue, src/components/bcros/filing/addStaffFiling/Index.vue
*Issue:*https://github.com/bcgov/entity/issues/24495
In business dashboard for a bootstrap business, the staff comment (in tombstone) and the 'Add Staff Filing' dropdown (in the header of the filing history section) should not be display. 
=> 24495 - staff comment and staff filing option should not be displayed for bootstrap business

src/components/bcros/businessDetails/Links.vue
*Issue:*https://github.com/bcgov/entity/issues/24459
Changed the function to not allow staff to change business info on not in good standing businesses
=> fix not in good standing staff change business information

src/components/bcros/businessDetails/Status.vue, src/components/bcros/filing/item/ConsentContinuationOut.vue, src/stores/business.ts, src/stores/filings.ts
*Issue:*https://github.com/bcgov/entity/issues/24375
- Fix the text display for Consent to Continue Out filing
- Display "AUTHORIZED TO CONTINUE OUT" in the tombstone
Example business: BC0883688
=> 'Consent to Continue Out' - fix filing history text and display badge in tombstone

src/components/bcros/Divider.vue, src/components/bcros/filing/CommonTemplate.vue, src/components/bcros/filing/common/FiledLabel.vue, src/components/bcros/filing/common/filedAnd/Paid.vue, src/components/bcros/filing/common/filedAnd/PendingCoa.vue, src/components/bcros/filing/common/filedAnd/PendingPaid.vue, src/components/bcros/filing/common/filedAnd/Rejected.vue, src/components/bcros/filing/common/futureEffective/Paid.vue, src/components/bcros/filing/item/StaffFiling.vue, src/components/bcros/pending/Item.vue, src/components/bcros/todo/content/ApprovedContinuationIn.vue, src/components/bcros/todo/content/ChangeRequested.vue, src/components/bcros/todo/content/Error.vue, src/components/bcros/todo/content/Paid.vue, src/components/bcros/todo/content/Pending.vue, src/components/bcros/tooltip/Date.vue, src/components/bcros/tooltip/index.vue, src/lang/en.json
*Issue:*https://github.com/bcgov/entity/issues/24391
=> Fix styling for filing history items

src/components/bcros/businessDetails/Links.vue
*Issue:*https://github.com/bcgov/entity/issues/24459
https://github.com/bcgov/business-dashboard-ui/pull/78
Change the condition for the modal to include staff  when not in good standing to fix which dialog shows
=> Fix which modal shows

src/components/bcros/businessDetails/Links.vue
*Issue:*https://github.com/bcgov/entity/issues/24459
Fix the text that shows for non staff user.
=> Fix for non staff user view/change business info modal

src/interfaces/business-i.ts, src/lang/en.json, src/stores/businessBootstrap.ts
*Issue:24638 *https://github.com/bcgov/entity/issues/24638 
fix: incorrect name in amalgamation application
=> 24638 - fix: incorrect name in amalgamation application

src/stores/businessBootstrap.ts
*Issue:*https://github.com/bcgov/entity/issues/24661
Change how legal type is looked at for bootstrap businesses. This fixes whatever is sending incorporation applications through without a business legal type in the business section of the filing.
=> fix for missing information on incorp requests

src/components/bcros/todo/Item.vue, src/utils/todo/task-filing/content-loader.ts
*Issue:*https://github.com/bcgov/entity/issues/24679
1) the draftTitle fields for IA draft and Registration draft were not loaded correctly, resulting in the 'undefined' in the deletion confirmation dialog. 
- IA draft: https://business-dashboard-dev--pr-97-5obencu4.web.app/TnjrzwbLE8
- Registration draft: https://business-dashboard-dev--pr-97-5obencu4.web.app/T1F4aVE2Sb
2) Additional fix (not mentioned in ticket #24679): when deleting a continuation authorization draft, "Continuation Authorization" is the right term to use in the dialog. 
- https://business-dashboard-dev--pr-97-5obencu4.web.app/TuRq0uvoEq
- https://business-dashboard-dev--pr-97-5obencu4.web.app/TfiJx520Uy
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> 24679 - fix 'undefined' text in dialog for deleting IA and registration

src/components/bcros/OfficeAddressBootstrap.vue, src/components/bcros/PartyInfo.vue, src/components/bcros/accordion/Index.vue, src/components/bcros/accordion/Item.vue, src/components/bcros/businessDetails/Links.vue, src/interfaces/accordion-item-i.ts, src/interfaces/bootstrap-i.ts, src/pages/dashboard.vue
*Issue:*https://github.com/bcgov/entity/issues/24689
Also https://github.com/bcgov/business-dashboard-ui/pull/94
Accidently chucked 94 so readded (see link above for more info)
Also set forth pulling information on future effective incorporations to show address and directors on bootstrap filings if the information is available.
=> Fix for future effective bootstrap business address and directors also #94

src/components/bcros/filing/CommonTemplate.vue
*Issue:*https://github.com/bcgov/entity/issues/24662
Change so that pressing detail also calls the api for document list
=> Fix for documents not loading when hitting details instead of show/hide

src/components/bcros/businessDetails/Header.vue, src/components/bcros/businessDetails/Status.vue
*Issue:*https://github.com/bcgov/entity/issues/24524
*Issue:*https://github.com/bcgov/entity/issues/24701
Fix date format for historical reason.
- Dissolved (already working) https://business-dashboard-dev--pr-99-id8t0fbc.web.app/FM1000026
- Amalgamated (fixed in this ticket, so the date does not include time) https://business-dashboard-dev--pr-99-id8t0fbc.web.app/BC0883658
- Continued out (already working) https://business-dashboard-dev--pr-99-id8t0fbc.web.app/BC0873705
Fix date format for 'active until' for limited restoration.
- https://business-dashboard-dev--pr-99-id8t0fbc.web.app/BC0883683
=> 24524 24701 fix date format in tombstone

src/components/bcros/Breadcrumb.vue
*Issue:*https://github.com/bcgov/entity/issues/24584
added the to value to the breadcrumbs so that they have a link value
=> link breadcrumbs to allow for open in new window

src/components/bcros/header/Index.vue, src/middleware/02.setupAuth.global.ts
*Issue:24755*https://github.com/bcgov/entity/issues/24755
fix: multiple accountid in the query param
=> fix: multiple accountid in the query param

src/composables/useBcrosAuth.ts, src/stores/account.ts
The username for BCeID user is not loaded properly (showing as 'undefined')
Problem resolved. See this screenshot taken from localhost
=> Fix username display for BCeID users

src/composables/useBcrosAuth.ts, src/stores/businessBootstrap.ts
When a bootstrap filing is completed (i.e. in Filing History), do not fetch NR. 
Example: 
https://business-dashboard-dev--pr-109-6wd9k1vn.web.app//THWqgK4Dnv
=> 24842 - bypass name request loading for completed bootstrap filing

src/components/bcros/filing/CommonTemplate.vue
*Issue:24821 *https://github.com/bcgov/entity/issues/24821 
fix: documents not loaded when filing expanded via URL query param
=> 24821 - fix for no documents on expanded screen.

src/components/bcros/LoadingIcon.vue, src/components/bcros/LoadingModal.vue, src/components/bcros/businessDetails/Links.vue, src/components/bcros/filing/CommonTemplate.vue, src/components/bcros/filing/common/HeaderActions.vue, src/lang/en.json, src/layouts/business.vue, src/layouts/default.vue, src/stores/ui.ts, src/utils/download-file.ts, src/utils/sleeps.ts
*Issue:*https://github.com/bcgov/entity/issues/24451
Re-organize code for the loading state spinner.
- Show "Loading Dashboard" spinner when the page is loading
- Show "Fetching Data" when the 1) downloading a business summary and 2) loading a document list
=> 24451 - Add the 'Fetching Data' spinner for downloading business summary and loading document lists

cypress/e2e/components/todos/pending.cy.ts, cypress/fixtures/todos/pendingCorrection.json, src/utils/todo/task-filing/content-loader.ts
*Issue:*https://github.com/bcgov/entity/issues/24458
When there is a pending correction in the todo section, no expansion panel should be displayed and there should be no 'view detail' button. 
It is hard to reproduce because a correction filing is added to the filing history right after the filing is submitted. 
Cypress test is used to mock this scenario. See screenshot below:
=> 24458 - no expansion panel for pending correction filing in the todo section

.env.example, devops/vaults.env, nuxt.config.ts, package.json, pnpm-lock.yaml, src/components/bcros/businessDetails/LinkActions.vue, src/composables/useBcrosNavigate.ts, src/interfaces/tasks-i.ts, src/interfaces/todo-i.ts, src/pages/dashboard.vue, src/utils/todo/action-functions.ts, src/utils/todo/task-filing/content-loader.ts, src/utils/todo/task-filing/index.ts
*Issue:*https://github.com/bcgov/entity/issues/24656
- Handle NoW Draft in ToDoList (Dashboard)
- Can resume and delete now
=> 24656 - Handle NoW Draft in ToDoList

cypress/e2e/components/filings/section.cy.ts, cypress/e2e/error-flows/download-error.cy.ts, src/components/bcros/businessDetails/Links.vue, src/components/bcros/dialog/CardedModal.vue, src/components/bcros/filing/CommonTemplate.vue, src/components/bcros/filing/common/HeaderActions.vue, src/lang/en.json, src/pages/dashboard.vue, src/stores/ui.ts, src/utils/download-file.ts, src/utils/error-dialog-options/download-file-error.ts
*Issue:*https://github.com/bcgov/entity/issues/25125
Add a dialog for download error for:
- downloading business summary
- downloading a document from filing history
Screenshots
=> 25125 - download error dialog

package.json, pnpm-lock.yaml, src/components/bcros/filing/common/HeaderActions.vue, src/components/bcros/filing/common/futureEffective/index.vue, src/lang/en.json
*Issue:*https://github.com/bcgov/entity/issues/24659 
- Implement withdraw action on ledger
**Try:**
Regular Businesss: https://business-dashboard-dev--pr-119-aql2sz14.web.app/BC0883803/?accountid=3627&accountid=3627
Bootstrap Business: https://business-dashboard-dev--pr-119-aql2sz14.web.app/TJes1p4Er5/?accountid=3627&accountid=3627
=> 24659 - Implement Withdraw Action in Ledger

package.json, src/components/bcros/businessDetails/Status.vue
*Issue:*https://github.com/bcgov/entity/issues/24779
The i18n text for "Unknown" was not displayed properly for unknown reason of a historical business.
When a business is historical and the filing type is "putBackOff" (e.g. Put back off filing due to expired limited restoration), the historical reason is "Unknown". 
Example in Dev: https://dev.business-dashboard.bcregistry.gov.bc.ca/BC0872094
In temp url: https://business-dashboard-dev--pr-122-zvwusqwp.web.app/BC0872094
=> 24779 - fix 'unknown' reason for historical business

package.json, src/app.config.ts, src/components/bcros/filing/addStaffFiling/Index.vue, src/components/bcros/filing/addStaffFiling/modal/Form.vue, src/pages/dashboard.vue, src/stores/business.ts
*Issue:*https://github.com/bcgov/entity/issues/23968
every 1 second until the 10 second mark
every 10 seconds until the 1 minute mark
every minute until the 30 minute mark
every hour thereafter
data polling slim end point , compare it with initial /identifier api endpoint's modified date, 
show toast msg if modified date vs slim endpoint modified date > 0s
=> Business Dashboard UI: implement background retry to check for latest state

package.json, src/components/bcros/filing/common/HeaderActions.vue
*Issue:*https://github.com/bcgov/entity/issues/25406
- Using `getStoredFlag `instead of `getFeatureFlag` as per https://github.com/bcgov/business-dashboard-ui/pull/127#:~:text=Yes%2C%20I%20believe%20that%20it%20would%20be%20better%20if%20getStoredFlag%20is%20used%20here%2C%20I%20do%20not%20think%20we%20used%20getFeatureFlag%20inside%20the%20vue%20files.%20It%20basically%20lets%20you%20retrieve%20flag%20(if%20loaded%20in%20the%20store)%20even%20if%20the%20ldclient%20is%20down.
=> 25406 - Use getStoredFlag to fetch Enable-Withdrawal-Action flag

cypress/e2e/components/filings/correctionFilings.cy.ts, package.json, src/components/bcros/businessDetails/Links.vue, src/components/bcros/comment/Index.vue
*Issue:*https://github.com/bcgov/entity/issues/25157
- We use the same modal to add comments and details. The modal does not close when the 'save' button is clicked. The issue is fixed in this PR
=> 25157 - close the comment modal after saving comments/details

package.json, pnpm-lock.yaml
*Issue:* bcgov/entity#26211
- app version = 1.0.22
- updated Keycloak JS dependency
=> 26211 Updated Keycloak dependency

package.json, src/components/bcros/filing/item/AlterationFiling.vue, src/components/bcros/filing/item/ContinuationOut.vue, src/components/bcros/filing/item/DissolutionVoluntary.vue, src/components/bcros/filing/item/LimitedRestoration.vue
*Issue:*https://github.com/bcgov/entity/issues/26293
- Add a 24px space below filing history status
- This update applies to Alteration, ContOut, VD, Limited Restoration.
=> 26293 - Add s space between filing history

package.json, src/components/bcros/filing/item/LimitedRestoration.vue
*Issue:*https://github.com/bcgov/entity/issues/25222
Removed nbsp from message build that was inserting a second space in sentence.
=> 25222-removing nbsp that was causing extra space in limited restoration

package.json, src/pages/dashboard.vue
*Issue:*https://github.com/bcgov/entity/issues/26368
- After a COA is withdrawn, it shouldn't show the Pending badge and tooltip
- Fix the pendingAddress condition to exclude withdrawn COA
=> 26368 - After a COA is withdrawn, don't show Pending badge

package.json, src/components/bcros/businessDetails/Links.vue, src/pages/dashboard.vue, src/stores/filings.ts
*Issue:* bcgov/entity#26499
- app version = 1.0.32
- changed navigateTo to goToEditUi or goToFilingsUi
- added a type to fix a lint warning
=> 26499 fixed redirects with missing accountId

package.json, src/pages/dashboard.vue, src/stores/business.ts
*Issue:*https://github.com/bcgov/entity/issues/26369 
- The bug happens in an intermediate stage when the state filing is not updated, however, once you **reload** the page (and the state filing is updated), you see the correct status & reasoning shown (i.e. if you go to the corp in the ticket, you'll see the correct status: 
)
- Solution: force the state filing to be updated on **refresh** (when you click the button that appears on the toast) to ensure the status shown is up-to-date
https://github.com/user-attachments/assets/f09a9a1f-7535-4c7b-a05d-ec1fc9e1255d
=> 26369 - Load State Filing on Dashboard Refresh 

cypress/e2e/components/addresses.cy.ts, package.json, src/plugins/bcros-fetch.ts
*Issue:* bcgov/entity#26471
I did the same as #3298 and used the verbose app name and not the package name:
- app version = 1.0.34
- added App Name header to all fetch calls
=> 26471 added App Name header

package.json, src/app/router.options.ts, src/components/bcros/filing/common/HeaderActions.vue
*Issue:* bcgov/entity#26719
- app version = 1.0.37
- changed default identifier to XXX (error handling)
- deleted obsolete modal instance
- allow corrections to paper-only filings
=> 26719 Allow corrections to paper-only filings

package.json, src/components/bcros/businessDetails/Links.vue, src/lang/en.json
- disable business summary for certain corp types and their continuation in countrerparts (BC, CC, ULC)
- update tooltip to match.
=> 26578 - feat: disable business summary for certain corp types

nuxt.config.ts, package.json, src/pages/dashboard.vue
*Issue:*https://github.com/bcgov/entity/issues/26644 
- Set the Business Dashboard page title to the Company Name
- Set the global title to "Business Dashboard"
- Update app version
=> 26644 - Set Business Dashboard Page Title to Company Name

package.json, src/pages/dashboard.vue
*Issue:*https://github.com/bcgov/entity/issues/26644
During testing it was discovered that a value different from the expected legal name was being displayed for SP and GP:
Now using the computed `currentBusinessName` property instead as it accounts for the alternate names for SP and GP.
=> 26644 - Fix Page Title for SP and GP

cypress.config.ts, cypress/e2e/components/addresses.cy.ts, package.json, src/stores/account.ts, src/stores/business.ts
*Issue:*https://github.com/bcgov/entity/issues/25048
Update so that we check account id query value against account id session value when setting up user on the dashboard. Assumed that session account id takes precedence. This addresses case where incorrect query param was overriding proper account id which caused issues with loading the proper account data.
=> 25048 add staff link now always displayed for staff

package.json, src/components/bcros/filing/item/AmalgamationOut.vue, src/components/bcros/filing/item/ConsentAmalgamationOut.vue, src/components/bcros/filing/item/ConsentContinuationOut.vue, src/components/bcros/filing/item/ContinuationOut.vue, tests/items/ForeignJurisdiction.spec.ts
*Issue:*https://github.com/bcgov/entity/issues/27509
- Update AO/CO/CAO/CCO jurisdiction in filing ledger 
- When the jurisdiction country is Canada and the jurisdiction "province" is Federal, we should only display the jurisdiction country
=> 27509 - Update AO/CO/CAO/CCO ledger jurisdiction

package.json, src/components/bcros/todo/expansion-content/PaymentPendingOnlineBanking.vue
*Issue:*https://github.com/bcgov/entity/issues/28454
- fix issue where the cfs account number was not displaying due to reactivity
=> 28454 - Fix reactivity on cfsAccountId

package.json, src/components/bcros/filing/common/FiledLabel.vue, src/components/bcros/filing/common/HeaderActions.vue, src/components/bcros/filing/common/filedAnd/Rejected.vue, src/components/bcros/filing/item/DissolutionVoluntary.vue, src/interfaces/filing-i.ts, src/interfaces/state-filing-i.ts, src/interfaces/tasks-i.ts, src/stores/filings.ts, src/utils/download-file.ts
*Issue:* bcgov/entity#29900
- app version = 1.1.10
- updated "filed by" date to be paymentDate if it exists, else fall back to submittedDate
=> 29900 use payment date if available

package.json, src/components/bcros/filing/common/FiledLabel.vue, src/components/bcros/tooltip/Date.vue
*Issue:* bcgov/entity#30724
- app version "1.1.15a" (hotfix)
- added special case to hide tooltip for COD
- updated BcrosTooltipDate to conditionally hide tooltip
Before:
After:
The above design change was approved by Janis.
=> 30724 Hide effective time for COD
